project:
  type: website
  resources:
  - revealjs-themed/
  - revealjs-themed-2/
  render:
  - index.qmd
  - revealjs-callout.qmd
  - revealjs-demo.qmd
website:
  title: Revealjs Themed Presentation
  search: false
  navbar:
    background: primary
    left:
    - href: index.qmd
      text: Home
    - text: Revealjs Demo Slides
      href: revealjs-demo.qmd
    - text: Callout in Revealjs
      href: revealjs-callout.qmd
format:
  html:
    theme: litera
